service: aws-app
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:

  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get


resources:
  Resources:

    myDynamoDBTable: 
      Type: AWS::DynamoDB::Table
      Properties: 
        AttributeDefinitions: 
          - 
            AttributeName: "Album"
            AttributeType: "S"
          - 
            AttributeName: "Artist"
            AttributeType: "S"
          - 
            AttributeName: "Sales"
            AttributeType: "N"
          - 
            AttributeName: "NumberOfSongs"
            AttributeType: "N"
        KeySchema: 
          - 
            AttributeName: "Album"
            KeyType: "HASH"
          - 
            AttributeName: "Artist"
            KeyType: "RANGE"
        ProvisionedThroughput: 
          ReadCapacityUnits: "5"
          WriteCapacityUnits: "5"
        TableName: "myTableName"


plugins:
  - serverless-offline
  - serverless-lift



constructs:
  
  frontend-app:
      type: static-website
      path: 'frontend-app/build'
